### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by unknown442** [unknown442/Software-Engineering-G14#6]
در این صفحه آخرین فعالیت های رخ داده در شبکه اجتماعی به هر کاربر نمایش داده میشود. شامل پستها، بلاگ ها، اخبار، مطلب تازه در انجمن ها، رویداد عمومی ایجاد شده، ویدیوهای جدید اضافه شده، تصویر جدید اضافه شده، مطلب تازه در یکی از گروه هایی که عضو است، یا فعایت یکی از دوستانش روی یکی از این موارد. ( پسندیدن یا کامنت گذاشتن )

**Comment by Gelareh-st** [comment]
نمونه ی اولیه این صفحه شامل پست، تصویر جدید، مطالب تازه در انجمن و مطالب پسندیده شده توسط دوستان، اضافه شد.
